bkdevops-projects/devops-framework

README.md

documentation: 完善文档 #65

---

README.md
buildSrc/src/main/kotlin/Versions.kt
devops-boot-project/devops-boot-dependencies/build.gradle.kts
devops-boot-project/devops-boot-tools/devops-boot-gradle-plugin/src/main/kotlin/com/tencent/devops/DevOpsBootPlugin.kt
devops-boot-sample/build.gradle.kts
docs/changelog.md
docs/index.md

Issue 89&92

---

devops-boot-project/devops-boot-dependencies/build.gradle.kts

bug: feign 10.10.1自动在header的value的逗号后面加空格, 导致获取到的值不符合预期

bug: dependencies自定义的版本没有生效

---

devops-boot-project/devops-boot-dependencies/build.gradle.kts

feat: 升级log4j到2.15.0 #111

---

devops-boot-project/devops-boot-dependencies/build.gradle.kts

feat : 升级logback版本 #114

---

devops-boot-project/devops-boot-tools/devops-boot-gradle-plugin/src/main/kotlin/com/tencent/devops/conventions/RepositoryConvention.kt

feat: 整理仓库配置 #110

---

devops-boot-project/devops-boot-tools/devops-boot-gradle-plugin/src/main/kotlin/com/tencent/devops/DevOpsBootPlugin.kt

bug: boot项目没有应用到devops-boot-dependencies #119

---

devops-boot-project/devops-boot-tools/devops-boot-gradle-plugin/src/main/kotlin/com/tencent/devops/utils/Constants.kt

feature: boot启动器新增property判断 #124

---

devops-boot-project/devops-boot-core/devops-pulsar/build.gradle.kts
devops-boot-project/devops-boot-dependencies/build.gradle.kts
devops-boot-project/devops-boot-starters/devops-boot-starter-stream-pulsar/build.gradle.kts
devops-boot-project/devops-boot-starters/devops-boot-starter-stream/build.gradle.kts

feature: 通过spring cloud stream方式支持pulsar bkdevops-projects#121

---

devops-boot-project/devops-boot-core/devops-pulsar/src/main/kotlin/com/tencent/devops/stream/binder/pulsar/PulsarMessageChannelBinder.kt
devops-boot-project/devops-boot-core/devops-pulsar/src/main/kotlin/com/tencent/devops/stream/binder/pulsar/autoconfigurate/PulsarBinderAutoConfiguration.kt
devops-boot-project/devops-boot-core/devops-pulsar/src/main/kotlin/com/tencent/devops/stream/binder/pulsar/constant/PulsarConstant.kt
devops-boot-project/devops-boot-core/devops-pulsar/src/main/kotlin/com/tencent/devops/stream/binder/pulsar/integration/inbound/PulsarConsumerFactory.kt
devops-boot-project/devops-boot-core/devops-pulsar/src/main/kotlin/com/tencent/devops/stream/binder/pulsar/integration/inbound/PulsarInboundChannelAdapter.kt
devops-boot-project/devops-boot-core/devops-pulsar/src/main/kotlin/com/tencent/devops/stream/binder/pulsar/integration/outbound/PulsarProducerFactory.kt
devops-boot-project/devops-boot-core/devops-pulsar/src/main/kotlin/com/tencent/devops/stream/binder/pulsar/integration/outbound/PulsarProducerMessageHandler.kt
devops-boot-project/devops-boot-core/devops-pulsar/src/main/kotlin/com/tencent/devops/stream/binder/pulsar/properties/PulsarBinderConfigurationProperties.kt
devops-boot-project/devops-boot-core/devops-pulsar/src/main/kotlin/com/tencent/devops/stream/binder/pulsar/properties/PulsarProperties.kt
devops-boot-project/devops-boot-core/devops-pulsar/src/main/kotlin/com/tencent/devops/stream/binder/pulsar/provisioning/PulsarMessageQueueProvisioner.kt
devops-boot-project/devops-boot-core/devops-pulsar/src/main/kotlin/com/tencent/devops/stream/binder/pulsar/util/PulsarClientUtils.kt
devops-boot-project/devops-boot-dependencies/build.gradle.kts

1 pulsar组件消费者需要支持并行消费；
2 pulsar组件支持可分别配置多个pulsar集群配置信息
3 pulsar增加生成延时消息功能

feature: 1 pulsar组件支持更多功能 bkdevops-projects#121

---

buildSrc/src/main/kotlin/Versions.kt
devops-boot-sample/gradle.properties

feat: 升级spring cloud 到 2020.0.3 #136

---

devops-boot-project/devops-boot-tools/devops-boot-gradle-plugin/src/main/kotlin/com/tencent/devops/conventions/RepositoryConvention.kt
devops-boot-sample/settings.gradle.kts
docs/dependency/repository.md

perf: 降低mavenLocal仓库优先级 #147

---

devops-boot-project/devops-boot-tools/devops-boot-gradle-plugin/src/main/kotlin/com/tencent/devops/conventions/RepositoryConvention.kt

feat: 升级相关框架版本 , 以支持kt1.6.21 #151

---

devops-boot-project/devops-boot-core/devops-plugin/devops-plugin-core/src/main/kotlin/com/tencent/devops/plugin/spring/PluginEndpoint.kt
devops-boot-project/devops-boot-core/devops-plugin/devops-plugin-core/src/main/kotlin/com/tencent/devops/plugin/spring/PluginEndpointAutoConfiguration.kt

feat: 默认关闭management.endpoint.devopsPlugin #155

---

.github/workflows/publish-snapshot.yml

chore: publish snapshot的流水线添加忽略路径，减少不必要的发布 #168

---

devops-boot-project/devops-boot-tools/devops-publish-gradle-plugin/src/main/kotlin/com/tencent/devops/DevOpsPublishPlugin.kt

bug: snapshot发布签名不通过 #181

---

build.gradle.kts
buildSrc/src/main/kotlin/Dependencies.kt
buildSrc/src/main/kotlin/Versions.kt
buildSrc/src/main/kotlin/publish.gradle.kts
devops-boot-project/devops-boot-tools/build.gradle.kts
devops-boot-project/devops-boot-tools/devops-boot-gradle-plugin/build.gradle.kts
devops-boot-project/devops-boot-tools/devops-gradle-plugin-common/build.gradle.kts
devops-boot-project/devops-boot-tools/devops-publish-gradle-plugin/build.gradle.kts
devops-boot-project/devops-boot-tools/devops-publish-gradle-plugin/src/main/kotlin/com/tencent/devops/DevOpsPublishPlugin.kt
devops-boot-project/devops-boot-tools/devops-release-gradle-plugin/build.gradle.kts

feat: devops-publish-gradle-plugin插件优化 #86

---

devops-boot-project/devops-boot-core/devops-web/src/main/kotlin/com/tencent/devops/web/swagger/SwaggerConfiguration.kt

feat: swagger支持basic auth #180

---

devops-boot-project/devops-boot-core/devops-common/build.gradle.kts
devops-boot-project/devops-boot-core/devops-common/src/main/kotlin/com/tencent/devops/common/crypto/AbstractCipherFactory.kt
devops-boot-project/devops-boot-core/devops-common/src/main/kotlin/com/tencent/devops/common/crypto/CipherFactoryProducer.kt
devops-boot-project/devops-boot-core/devops-common/src/main/kotlin/com/tencent/devops/common/crypto/EncryptInputStream.kt
devops-boot-project/devops-boot-core/devops-common/src/main/kotlin/com/tencent/devops/common/crypto/SM4EncryptInputStream.kt
devops-boot-project/devops-boot-core/devops-common/src/main/kotlin/com/tencent/devops/common/crypto/SM4Factory.kt
devops-boot-project/devops-boot-core/devops-common/src/test/kotlin/com/tencent/devops/common/crypto/CryptoTest.kt
devops-boot-project/devops-boot-dependencies/build.gradle.kts

feat: 增加common模块，支持国密 #186

---

devops-boot-project/devops-boot-tools/devops-boot-gradle-plugin/src/main/kotlin/com/tencent/devops/conventions/RepositoryConvention.kt

fix: devops-boot-gradle-plugin 修改仓库配置顺序 #244
